// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Database;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    [Migration("20221129133552_v3")]
    partial class v3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentManagementSystem.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Credits")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("37de63d6-11a7-4087-b94e-6cad79940a01"),
                            Credits = 15,
                            Name = "Math"
                        },
                        new
                        {
                            Id = new Guid("6b7e4bc0-f86e-4a24-8873-b597dcd795fd"),
                            Credits = 13,
                            Name = "Science"
                        },
                        new
                        {
                            Id = new Guid("2877cf21-45d6-47ad-901d-917b584f4dc8"),
                            Credits = 15,
                            Name = "Portuguese"
                        },
                        new
                        {
                            Id = new Guid("029f74d2-4fbe-4ddf-83bb-a40a77c955ba"),
                            Credits = 10,
                            Name = "Sport"
                        },
                        new
                        {
                            Id = new Guid("d56090d8-45ca-4b2a-8fb4-0577b071c512"),
                            Credits = 9,
                            Name = "Philosophy"
                        },
                        new
                        {
                            Id = new Guid("188f9120-bc51-4530-a3bd-00b735e3ab29"),
                            Credits = 13,
                            Name = "English"
                        },
                        new
                        {
                            Id = new Guid("5f03ad07-451f-41ce-9d4b-60aca4b8b655"),
                            Credits = 12,
                            Name = "Politics"
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Entities.Disenrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Disenrollments");
                });

            modelBuilder.Entity("StudentManagementSystem.Entities.Enrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e38b49de-7909-4e99-864b-d4d8ce5f858a"),
                            CourseId = new Guid("37de63d6-11a7-4087-b94e-6cad79940a01"),
                            Grade = 1,
                            StudentId = new Guid("a055b09a-1d0f-4a2d-8626-a5ad51ce685e")
                        },
                        new
                        {
                            Id = new Guid("5a560340-392e-4eb6-9151-f70301ff34c1"),
                            CourseId = new Guid("2877cf21-45d6-47ad-901d-917b584f4dc8"),
                            Grade = 2,
                            StudentId = new Guid("a055b09a-1d0f-4a2d-8626-a5ad51ce685e")
                        },
                        new
                        {
                            Id = new Guid("db0d4bc3-45e2-4b3f-b457-086adf9c7fa1"),
                            CourseId = new Guid("37de63d6-11a7-4087-b94e-6cad79940a01"),
                            Grade = 2,
                            StudentId = new Guid("8f55d259-2d55-4aef-9c65-3c93f905e932")
                        },
                        new
                        {
                            Id = new Guid("d15ed3a0-3737-4de7-a491-18c23c57003e"),
                            CourseId = new Guid("2877cf21-45d6-47ad-901d-917b584f4dc8"),
                            Grade = 3,
                            StudentId = new Guid("8f55d259-2d55-4aef-9c65-3c93f905e932")
                        },
                        new
                        {
                            Id = new Guid("2d7f26b8-b1d3-467a-bf23-5bb9919ea110"),
                            CourseId = new Guid("37de63d6-11a7-4087-b94e-6cad79940a01"),
                            Grade = 0,
                            StudentId = new Guid("cfd3b928-5fb8-46a7-b453-7e4e878f16e3")
                        },
                        new
                        {
                            Id = new Guid("4c2d45d5-aaa9-4b36-a2fa-95d85d65d62d"),
                            CourseId = new Guid("2877cf21-45d6-47ad-901d-917b584f4dc8"),
                            Grade = 1,
                            StudentId = new Guid("cfd3b928-5fb8-46a7-b453-7e4e878f16e3")
                        },
                        new
                        {
                            Id = new Guid("bbf19f2d-bcd6-40b3-b5d4-5da009b3036e"),
                            CourseId = new Guid("37de63d6-11a7-4087-b94e-6cad79940a01"),
                            Grade = 4,
                            StudentId = new Guid("66474f33-77bc-4ee2-b23e-8ecc8ba907a1")
                        },
                        new
                        {
                            Id = new Guid("1bf274b6-02b0-4c60-bde7-179f280f37f4"),
                            CourseId = new Guid("2877cf21-45d6-47ad-901d-917b584f4dc8"),
                            Grade = 4,
                            StudentId = new Guid("66474f33-77bc-4ee2-b23e-8ecc8ba907a1")
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a055b09a-1d0f-4a2d-8626-a5ad51ce685e"),
                            Email = "student1@email.com",
                            Name = "student 1"
                        },
                        new
                        {
                            Id = new Guid("8f55d259-2d55-4aef-9c65-3c93f905e932"),
                            Email = "student2@email.com",
                            Name = "student 2"
                        },
                        new
                        {
                            Id = new Guid("cfd3b928-5fb8-46a7-b453-7e4e878f16e3"),
                            Email = "student3@email.com",
                            Name = "student 3"
                        },
                        new
                        {
                            Id = new Guid("66474f33-77bc-4ee2-b23e-8ecc8ba907a1"),
                            Email = "student4@email.com",
                            Name = "student 4"
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Entities.Disenrollment", b =>
                {
                    b.HasOne("StudentManagementSystem.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.Entities.Student", "Student")
                        .WithMany("Disenrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentManagementSystem.Entities.Enrollment", b =>
                {
                    b.HasOne("StudentManagementSystem.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.Entities.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentManagementSystem.Entities.Student", b =>
                {
                    b.Navigation("Disenrollments");

                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
