// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Database;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    partial class SchoolDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentManagementSystem.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Credits")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b9aa3a2c-36b8-4ab7-91e5-afdf1c901e1c"),
                            Credits = 9,
                            Name = "Bachelor of Performing Arts"
                        },
                        new
                        {
                            Id = new Guid("0f650700-8954-4d40-a463-965ac4a2af5f"),
                            Credits = 23,
                            Name = "Construction Engineering"
                        },
                        new
                        {
                            Id = new Guid("a5103dba-56db-421f-867d-b50d78b217eb"),
                            Credits = 6,
                            Name = "Instrumentation Engineering"
                        },
                        new
                        {
                            Id = new Guid("70de1eb7-991a-4583-b3da-b6f29300045c"),
                            Credits = 5,
                            Name = "Structural Engineering"
                        },
                        new
                        {
                            Id = new Guid("302981e8-4922-4bcb-8695-9304d754a2dc"),
                            Credits = 16,
                            Name = "BTTM- Bachelor of Travel and Tourism Management"
                        },
                        new
                        {
                            Id = new Guid("a7402094-4232-42b3-9022-43b49cf537d2"),
                            Credits = 18,
                            Name = "Biotechnology Engineering"
                        },
                        new
                        {
                            Id = new Guid("4e09a068-d7db-4451-aff8-bb0c4706a55b"),
                            Credits = 23,
                            Name = "BMS- Bachelor of Management Science"
                        },
                        new
                        {
                            Id = new Guid("c894d5b4-962b-4832-91dd-6c8250e35839"),
                            Credits = 24,
                            Name = "Construction Engineering"
                        },
                        new
                        {
                            Id = new Guid("0e9fe44d-185c-4dc9-aba9-208de7d36cfe"),
                            Credits = 21,
                            Name = "Electrical and Electronics Engineering"
                        },
                        new
                        {
                            Id = new Guid("0e882e0e-06dc-49a7-ada0-869674c9b5ab"),
                            Credits = 5,
                            Name = "Electrical and Electronics Engineering"
                        },
                        new
                        {
                            Id = new Guid("cf65b6dc-99b3-4148-95da-ba5f675769b6"),
                            Credits = 20,
                            Name = "Bachelor of Performing Arts"
                        },
                        new
                        {
                            Id = new Guid("9a6187c0-95a6-40ca-aaa9-ac2d91a7fd65"),
                            Credits = 17,
                            Name = "Ceramic Engineering"
                        },
                        new
                        {
                            Id = new Guid("b44b6646-9828-471f-8f4b-31775857f812"),
                            Credits = 1,
                            Name = "Instrumentation Engineering"
                        },
                        new
                        {
                            Id = new Guid("b213e3e5-42b1-4715-8b87-18b0da21d8a5"),
                            Credits = 8,
                            Name = "BBA- Bachelor of Business Administration"
                        },
                        new
                        {
                            Id = new Guid("4c7a9083-5000-4739-8f6d-d94a90524173"),
                            Credits = 23,
                            Name = "Automation and Robotics"
                        },
                        new
                        {
                            Id = new Guid("3a770f67-66a7-45d9-8923-db4e81bd1663"),
                            Credits = 11,
                            Name = "B.Sc- Interior Design"
                        },
                        new
                        {
                            Id = new Guid("57f07cc7-2861-449d-975a-0993c1646693"),
                            Credits = 28,
                            Name = "BFA- Bachelor of Fine Arts"
                        },
                        new
                        {
                            Id = new Guid("f66cec31-5c36-495f-a3e8-a632a69e7f95"),
                            Credits = 3,
                            Name = "Power Engineering"
                        },
                        new
                        {
                            Id = new Guid("1674c76c-ac10-46bf-955d-0f9309f7177c"),
                            Credits = 6,
                            Name = "Aeronautical Engineering"
                        },
                        new
                        {
                            Id = new Guid("6a25e83a-1356-429c-9aea-d30fb0b9dece"),
                            Credits = 11,
                            Name = "BSW- Bachelor of Social Work"
                        },
                        new
                        {
                            Id = new Guid("8572ef17-1801-4c46-976c-7bdd72686b22"),
                            Credits = 8,
                            Name = "Petroleum Engineering"
                        },
                        new
                        {
                            Id = new Guid("97e6e2a2-c6c9-4a98-80ac-cd1c8652dade"),
                            Credits = 6,
                            Name = "Construction Engineering"
                        },
                        new
                        {
                            Id = new Guid("e29a950e-3d26-4e41-8dce-7d80df4f881e"),
                            Credits = 0,
                            Name = "Robotics Engineering"
                        },
                        new
                        {
                            Id = new Guid("5ea497be-a068-4263-bfc4-c6914fe82262"),
                            Credits = 1,
                            Name = "BFD- Bachelor of Fashion Designing"
                        },
                        new
                        {
                            Id = new Guid("eef738ff-7d6c-4d91-ac1b-71948ba0f351"),
                            Credits = 17,
                            Name = "BTTM- Bachelor of Travel and Tourism Management"
                        },
                        new
                        {
                            Id = new Guid("89a7cfc9-c176-4c0c-897a-85a72af27328"),
                            Credits = 22,
                            Name = "Integrated Law Course- BA + LL.B"
                        },
                        new
                        {
                            Id = new Guid("dc5dfd82-7ce4-4b3a-ad36-4ff9a47ba5c3"),
                            Credits = 12,
                            Name = "Aviation Courses"
                        },
                        new
                        {
                            Id = new Guid("a9123ad1-a12d-4cb5-976b-8791b693d938"),
                            Credits = 26,
                            Name = "Computer Science and Engineering"
                        },
                        new
                        {
                            Id = new Guid("74b14e45-1e6e-4b86-9ed4-1e9f6e82dde4"),
                            Credits = 7,
                            Name = "BFD- Bachelor of Fashion Designing"
                        },
                        new
                        {
                            Id = new Guid("5bd560d4-fd65-4d8b-a29b-e78710d28e27"),
                            Credits = 19,
                            Name = "Biotechnology Engineering"
                        },
                        new
                        {
                            Id = new Guid("21166334-aca5-4b50-ad64-d0880a6d9ee3"),
                            Credits = 11,
                            Name = "BTTM- Bachelor of Travel and Tourism Management"
                        },
                        new
                        {
                            Id = new Guid("c986bce5-2f09-419c-829e-2125a44bc222"),
                            Credits = 28,
                            Name = "Smart Manufacturing & Automation"
                        },
                        new
                        {
                            Id = new Guid("48719fec-da6e-4132-a2e2-e55a295f666d"),
                            Credits = 25,
                            Name = "Civil Engineering"
                        },
                        new
                        {
                            Id = new Guid("d3bc773b-97a9-4078-897c-decfd6bfffc6"),
                            Credits = 15,
                            Name = "Electronics and Communication Engineering"
                        },
                        new
                        {
                            Id = new Guid("29335e30-c60c-4c8b-8310-3f4f41fb92e7"),
                            Credits = 21,
                            Name = "Textile Engineering"
                        },
                        new
                        {
                            Id = new Guid("4eb78ab4-3578-4e72-b83e-643d9fc5f010"),
                            Credits = 11,
                            Name = "Electronics and Communication Engineering"
                        },
                        new
                        {
                            Id = new Guid("48517df9-b7ad-4831-a7c2-e3e632207eda"),
                            Credits = 7,
                            Name = "Robotics Engineering"
                        },
                        new
                        {
                            Id = new Guid("5de57509-18e6-4a26-a0b9-02b49a0b736c"),
                            Credits = 8,
                            Name = "Civil Engineering"
                        },
                        new
                        {
                            Id = new Guid("97554ca0-1a4c-43b8-a2b6-f8f5f5948aad"),
                            Credits = 15,
                            Name = "Transportation Engineering"
                        },
                        new
                        {
                            Id = new Guid("1aa44c1b-d9db-4050-a55d-04a625c1c24c"),
                            Credits = 24,
                            Name = "Chemical Engineering"
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Entities.Disenrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Disenrollments");
                });

            modelBuilder.Entity("StudentManagementSystem.Entities.Enrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b19ec2bd-da6d-41a3-a700-5a9399597dce"),
                            CourseId = new Guid("48719fec-da6e-4132-a2e2-e55a295f666d"),
                            Grade = 5,
                            StudentId = new Guid("284df7d9-b086-42ea-9a2c-d5f1d1b0d649")
                        },
                        new
                        {
                            Id = new Guid("3c2b8474-dcba-4048-85e2-b09606ba207b"),
                            CourseId = new Guid("4e09a068-d7db-4451-aff8-bb0c4706a55b"),
                            Grade = 4,
                            StudentId = new Guid("118c7a1c-6981-4d50-a2fb-b5ad7229e67b")
                        },
                        new
                        {
                            Id = new Guid("bbb11aa3-bdb2-4ee6-b4dc-e58cf1a32af5"),
                            CourseId = new Guid("0e882e0e-06dc-49a7-ada0-869674c9b5ab"),
                            Grade = 1,
                            StudentId = new Guid("59669200-1e95-4f3d-bb0d-7b05012a2d4a")
                        },
                        new
                        {
                            Id = new Guid("d68a9699-1360-4189-89b8-80ac5c6b9077"),
                            CourseId = new Guid("cf65b6dc-99b3-4148-95da-ba5f675769b6"),
                            Grade = 2,
                            StudentId = new Guid("c29465fe-440c-4b2e-9d0c-8ee326201783")
                        },
                        new
                        {
                            Id = new Guid("dc29efc7-4f20-4ba7-8928-1769b13be6f4"),
                            CourseId = new Guid("b9aa3a2c-36b8-4ab7-91e5-afdf1c901e1c"),
                            Grade = 4,
                            StudentId = new Guid("70297587-16e4-4226-8841-3a94b21bc75a")
                        },
                        new
                        {
                            Id = new Guid("adfe1028-e2c8-4081-9622-89d9da921e6b"),
                            CourseId = new Guid("c986bce5-2f09-419c-829e-2125a44bc222"),
                            Grade = 5,
                            StudentId = new Guid("7a4298cf-ba36-4a69-b7fa-097265e2a2ef")
                        },
                        new
                        {
                            Id = new Guid("b3b9f85a-cc5a-403e-bf0c-fcf39873834c"),
                            CourseId = new Guid("b44b6646-9828-471f-8f4b-31775857f812"),
                            Grade = 5,
                            StudentId = new Guid("c29465fe-440c-4b2e-9d0c-8ee326201783")
                        },
                        new
                        {
                            Id = new Guid("7a5f3f70-3d04-4dc4-becf-600f3c9786d3"),
                            CourseId = new Guid("dc5dfd82-7ce4-4b3a-ad36-4ff9a47ba5c3"),
                            Grade = 3,
                            StudentId = new Guid("c0f8373b-6e54-4550-b637-470ee8201d4a")
                        },
                        new
                        {
                            Id = new Guid("74bd7cc9-5988-40bf-9424-00792b3436a8"),
                            CourseId = new Guid("1674c76c-ac10-46bf-955d-0f9309f7177c"),
                            Grade = 1,
                            StudentId = new Guid("5c59c4ad-328f-4b59-9599-fb7a3662235e")
                        },
                        new
                        {
                            Id = new Guid("61296734-136c-41de-80cb-01200891afab"),
                            CourseId = new Guid("4eb78ab4-3578-4e72-b83e-643d9fc5f010"),
                            Grade = 4,
                            StudentId = new Guid("5a50784a-c1a0-4d9e-9d2e-3350dbf762c4")
                        },
                        new
                        {
                            Id = new Guid("7f07e3ec-ecef-4700-b53a-4446b0a5d788"),
                            CourseId = new Guid("4c7a9083-5000-4739-8f6d-d94a90524173"),
                            Grade = 5,
                            StudentId = new Guid("59669200-1e95-4f3d-bb0d-7b05012a2d4a")
                        },
                        new
                        {
                            Id = new Guid("c9148f41-6abb-4862-a0de-58bd8a71bcaa"),
                            CourseId = new Guid("57f07cc7-2861-449d-975a-0993c1646693"),
                            Grade = 5,
                            StudentId = new Guid("5eef45df-e07f-40a2-b20b-a92956858580")
                        },
                        new
                        {
                            Id = new Guid("7eb59d7d-85fc-4daf-9d54-75c680da825a"),
                            CourseId = new Guid("302981e8-4922-4bcb-8695-9304d754a2dc"),
                            Grade = 3,
                            StudentId = new Guid("c29465fe-440c-4b2e-9d0c-8ee326201783")
                        },
                        new
                        {
                            Id = new Guid("0819683b-f394-4455-8dc0-e803e006258a"),
                            CourseId = new Guid("9a6187c0-95a6-40ca-aaa9-ac2d91a7fd65"),
                            Grade = 5,
                            StudentId = new Guid("5a50784a-c1a0-4d9e-9d2e-3350dbf762c4")
                        },
                        new
                        {
                            Id = new Guid("011f6f39-3386-492a-a976-9e1aa0190585"),
                            CourseId = new Guid("f66cec31-5c36-495f-a3e8-a632a69e7f95"),
                            Grade = 5,
                            StudentId = new Guid("5781bfe3-41f5-4adf-be5f-13d9576efd55")
                        },
                        new
                        {
                            Id = new Guid("45eaaa26-8d18-4853-97e3-bf21beb951b4"),
                            CourseId = new Guid("5bd560d4-fd65-4d8b-a29b-e78710d28e27"),
                            Grade = 3,
                            StudentId = new Guid("5b18eb20-62e9-473d-b265-91ab876a142e")
                        },
                        new
                        {
                            Id = new Guid("9d032a5d-845e-4a42-b33d-a8dee7933a8b"),
                            CourseId = new Guid("a7402094-4232-42b3-9022-43b49cf537d2"),
                            Grade = 5,
                            StudentId = new Guid("025560e1-5f25-46b5-b80e-bbabe64de8bd")
                        },
                        new
                        {
                            Id = new Guid("d7ca0cf6-cb2c-456a-8a8f-02823eae4cc6"),
                            CourseId = new Guid("a7402094-4232-42b3-9022-43b49cf537d2"),
                            Grade = 1,
                            StudentId = new Guid("639724e7-174b-4319-a68c-222fe0df463a")
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5a50784a-c1a0-4d9e-9d2e-3350dbf762c4"),
                            Email = "Jeannie_Lind31@gmail.com",
                            Name = "Jeannie Lind"
                        },
                        new
                        {
                            Id = new Guid("500d1810-5864-49e4-8b13-2d7cf80e3e76"),
                            Email = "Jill.Sauer41@gmail.com",
                            Name = "Jill Sauer"
                        },
                        new
                        {
                            Id = new Guid("59669200-1e95-4f3d-bb0d-7b05012a2d4a"),
                            Email = "Danny_Waters@hotmail.com",
                            Name = "Danny Waters"
                        },
                        new
                        {
                            Id = new Guid("025560e1-5f25-46b5-b80e-bbabe64de8bd"),
                            Email = "Jessie_Gutkowski@gmail.com",
                            Name = "Jessie Gutkowski"
                        },
                        new
                        {
                            Id = new Guid("b237b1f8-545d-49f8-83ec-c6f9f1c7c0f4"),
                            Email = "Jenny.Blick@gmail.com",
                            Name = "Jenny Blick"
                        },
                        new
                        {
                            Id = new Guid("284df7d9-b086-42ea-9a2c-d5f1d1b0d649"),
                            Email = "Constance22@gmail.com",
                            Name = "Constance Kassulke"
                        },
                        new
                        {
                            Id = new Guid("5eef45df-e07f-40a2-b20b-a92956858580"),
                            Email = "Bonnie.Beer@yahoo.com",
                            Name = "Bonnie Beer"
                        },
                        new
                        {
                            Id = new Guid("118c7a1c-6981-4d50-a2fb-b5ad7229e67b"),
                            Email = "Eileen97@yahoo.com",
                            Name = "Eileen Roberts"
                        },
                        new
                        {
                            Id = new Guid("c0f8373b-6e54-4550-b637-470ee8201d4a"),
                            Email = "Frederick92@hotmail.com",
                            Name = "Frederick Mohr"
                        },
                        new
                        {
                            Id = new Guid("c29465fe-440c-4b2e-9d0c-8ee326201783"),
                            Email = "John.Labadie@hotmail.com",
                            Name = "John Labadie"
                        },
                        new
                        {
                            Id = new Guid("5c59c4ad-328f-4b59-9599-fb7a3662235e"),
                            Email = "Mabel_Schiller55@hotmail.com",
                            Name = "Mabel Schiller"
                        },
                        new
                        {
                            Id = new Guid("a4c105cc-a6e4-4e6f-9ee6-5a5c7c994aa1"),
                            Email = "Frederick80@hotmail.com",
                            Name = "Frederick Blanda"
                        },
                        new
                        {
                            Id = new Guid("6e58d3c9-0249-4a98-b803-87511b0757a5"),
                            Email = "Vicki_Waelchi@hotmail.com",
                            Name = "Vicki Waelchi"
                        },
                        new
                        {
                            Id = new Guid("3a5d9320-0d5e-438b-b15c-da2967bd624c"),
                            Email = "Luis_Towne@gmail.com",
                            Name = "Luis Towne"
                        },
                        new
                        {
                            Id = new Guid("5c921f64-843b-4abd-91ff-029047006111"),
                            Email = "Fredrick_Gusikowski@gmail.com",
                            Name = "Fredrick Gusikowski"
                        },
                        new
                        {
                            Id = new Guid("0bbfa698-a58e-41d3-9e0c-ab305f234451"),
                            Email = "Angela_Smith@gmail.com",
                            Name = "Angela Smith"
                        },
                        new
                        {
                            Id = new Guid("5781bfe3-41f5-4adf-be5f-13d9576efd55"),
                            Email = "Rickey_Okuneva61@gmail.com",
                            Name = "Rickey Okuneva"
                        },
                        new
                        {
                            Id = new Guid("7a4298cf-ba36-4a69-b7fa-097265e2a2ef"),
                            Email = "May36@hotmail.com",
                            Name = "May Schoen"
                        },
                        new
                        {
                            Id = new Guid("5b18eb20-62e9-473d-b265-91ab876a142e"),
                            Email = "Robyn.Rutherford@yahoo.com",
                            Name = "Robyn Rutherford"
                        },
                        new
                        {
                            Id = new Guid("bd5ea150-2973-406f-b7a8-b608bca698cf"),
                            Email = "Kerry73@gmail.com",
                            Name = "Kerry Gutmann"
                        },
                        new
                        {
                            Id = new Guid("2ce62faf-5049-492e-8b96-a3cb2c4565be"),
                            Email = "Frederick_Bartell@hotmail.com",
                            Name = "Frederick Bartell"
                        },
                        new
                        {
                            Id = new Guid("91c5bc2a-da4a-480c-990a-6ba483d85f8a"),
                            Email = "Ismael.Nitzsche@hotmail.com",
                            Name = "Ismael Nitzsche"
                        },
                        new
                        {
                            Id = new Guid("3b6cc267-1421-4e63-9a63-be455e79cfd6"),
                            Email = "Marcella75@yahoo.com",
                            Name = "Marcella Grady"
                        },
                        new
                        {
                            Id = new Guid("49184e54-00e6-40a7-91c7-817c6ad24538"),
                            Email = "Noel_Abernathy@hotmail.com",
                            Name = "Noel Abernathy"
                        },
                        new
                        {
                            Id = new Guid("68bf494a-4479-4e58-bc62-2bc8c13da6e1"),
                            Email = "Ramona_Schneider@gmail.com",
                            Name = "Ramona Schneider"
                        },
                        new
                        {
                            Id = new Guid("6d4a1f2e-1644-4621-a3f7-df7822ab2982"),
                            Email = "Judith.Mertz@hotmail.com",
                            Name = "Judith Mertz"
                        },
                        new
                        {
                            Id = new Guid("84e7cc19-6e5a-448c-a48e-1b38d9cf7608"),
                            Email = "Maxine_Luettgen5@yahoo.com",
                            Name = "Maxine Luettgen"
                        },
                        new
                        {
                            Id = new Guid("639724e7-174b-4319-a68c-222fe0df463a"),
                            Email = "Pablo_Price@yahoo.com",
                            Name = "Pablo Price"
                        },
                        new
                        {
                            Id = new Guid("70297587-16e4-4226-8841-3a94b21bc75a"),
                            Email = "Joyce89@hotmail.com",
                            Name = "Joyce Armstrong"
                        },
                        new
                        {
                            Id = new Guid("991213e8-8f7e-4a3d-9199-e02c3c5dd8e1"),
                            Email = "Grace87@gmail.com",
                            Name = "Grace Kunde"
                        },
                        new
                        {
                            Id = new Guid("11133fca-5193-47a5-abe8-533c6d7c2f6a"),
                            Email = "Rex79@yahoo.com",
                            Name = "Rex Kuhlman"
                        },
                        new
                        {
                            Id = new Guid("0b46d90b-5e67-481a-ada5-5a7e7258ea16"),
                            Email = "Shannon.Fahey29@hotmail.com",
                            Name = "Shannon Fahey"
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Entities.Disenrollment", b =>
                {
                    b.HasOne("StudentManagementSystem.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.Entities.Student", "Student")
                        .WithMany("Disenrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentManagementSystem.Entities.Enrollment", b =>
                {
                    b.HasOne("StudentManagementSystem.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.Entities.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentManagementSystem.Entities.Student", b =>
                {
                    b.Navigation("Disenrollments");

                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
