// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Database;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    [Migration("20221129133659_v4")]
    partial class v4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentManagementSystem.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Credits")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("680508d2-e5cc-438e-b3a6-027604c81a9b"),
                            Credits = 15,
                            Name = "Math"
                        },
                        new
                        {
                            Id = new Guid("38094811-dc2c-4572-a544-70e6d93376a3"),
                            Credits = 13,
                            Name = "Science"
                        },
                        new
                        {
                            Id = new Guid("7b144848-d7be-4be1-a320-66a9b71e1b97"),
                            Credits = 15,
                            Name = "Portuguese"
                        },
                        new
                        {
                            Id = new Guid("bedc2129-5ae8-4a2d-aa6a-9e7be7b8825c"),
                            Credits = 10,
                            Name = "Sport"
                        },
                        new
                        {
                            Id = new Guid("c978ea3e-7583-41ba-b04a-b9257aea2731"),
                            Credits = 9,
                            Name = "Philosophy"
                        },
                        new
                        {
                            Id = new Guid("d2f80086-3bc5-493a-ba62-4a561c8cfd2f"),
                            Credits = 13,
                            Name = "English"
                        },
                        new
                        {
                            Id = new Guid("24816d8d-ba43-4eb1-8430-7434bcf03380"),
                            Credits = 12,
                            Name = "Politics"
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Entities.Disenrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Disenrollments");
                });

            modelBuilder.Entity("StudentManagementSystem.Entities.Enrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2ff82a0b-f67a-48bb-bc14-3a9c1c2ab56b"),
                            CourseId = new Guid("680508d2-e5cc-438e-b3a6-027604c81a9b"),
                            Grade = 1,
                            StudentId = new Guid("f57cfdc7-7f1a-43d2-a69c-e6ae77c56d90")
                        },
                        new
                        {
                            Id = new Guid("b9b811c7-d27a-44b0-b0ff-56fc3bbb29e1"),
                            CourseId = new Guid("7b144848-d7be-4be1-a320-66a9b71e1b97"),
                            Grade = 2,
                            StudentId = new Guid("f57cfdc7-7f1a-43d2-a69c-e6ae77c56d90")
                        },
                        new
                        {
                            Id = new Guid("de174bac-1b14-4ff2-8dba-13571ea53971"),
                            CourseId = new Guid("680508d2-e5cc-438e-b3a6-027604c81a9b"),
                            Grade = 2,
                            StudentId = new Guid("537874a4-990d-4e06-878a-cc462c3aac14")
                        },
                        new
                        {
                            Id = new Guid("3cbcbcc1-573d-4bc5-a565-d47bf2b982d4"),
                            CourseId = new Guid("7b144848-d7be-4be1-a320-66a9b71e1b97"),
                            Grade = 3,
                            StudentId = new Guid("537874a4-990d-4e06-878a-cc462c3aac14")
                        },
                        new
                        {
                            Id = new Guid("c6c05962-cbb0-4e8f-b810-005f968a9280"),
                            CourseId = new Guid("680508d2-e5cc-438e-b3a6-027604c81a9b"),
                            Grade = 1,
                            StudentId = new Guid("44009547-fc6c-4702-b044-0786cd3e70b8")
                        },
                        new
                        {
                            Id = new Guid("a8360959-6cd9-46e5-b738-f886755ac24b"),
                            CourseId = new Guid("7b144848-d7be-4be1-a320-66a9b71e1b97"),
                            Grade = 1,
                            StudentId = new Guid("44009547-fc6c-4702-b044-0786cd3e70b8")
                        },
                        new
                        {
                            Id = new Guid("959c6725-0801-49fc-986a-80d7a6240466"),
                            CourseId = new Guid("680508d2-e5cc-438e-b3a6-027604c81a9b"),
                            Grade = 4,
                            StudentId = new Guid("3231ff4b-3aca-4896-971a-1163b27ed277")
                        },
                        new
                        {
                            Id = new Guid("653997ca-b240-489c-adcd-0dc529b62752"),
                            CourseId = new Guid("7b144848-d7be-4be1-a320-66a9b71e1b97"),
                            Grade = 4,
                            StudentId = new Guid("3231ff4b-3aca-4896-971a-1163b27ed277")
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f57cfdc7-7f1a-43d2-a69c-e6ae77c56d90"),
                            Email = "student1@email.com",
                            Name = "student 1"
                        },
                        new
                        {
                            Id = new Guid("537874a4-990d-4e06-878a-cc462c3aac14"),
                            Email = "student2@email.com",
                            Name = "student 2"
                        },
                        new
                        {
                            Id = new Guid("44009547-fc6c-4702-b044-0786cd3e70b8"),
                            Email = "student3@email.com",
                            Name = "student 3"
                        },
                        new
                        {
                            Id = new Guid("3231ff4b-3aca-4896-971a-1163b27ed277"),
                            Email = "student4@email.com",
                            Name = "student 4"
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Entities.Disenrollment", b =>
                {
                    b.HasOne("StudentManagementSystem.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.Entities.Student", "Student")
                        .WithMany("Disenrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentManagementSystem.Entities.Enrollment", b =>
                {
                    b.HasOne("StudentManagementSystem.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.Entities.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentManagementSystem.Entities.Student", b =>
                {
                    b.Navigation("Disenrollments");

                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
