// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Database;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    [Migration("20221129133138_v2")]
    partial class v2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentManagementSystem.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Credits")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1ec42a3c-9fb8-4148-b6ec-93a235ce6493"),
                            Credits = 15,
                            Name = "Math"
                        },
                        new
                        {
                            Id = new Guid("13b7c797-1cf4-4dc4-9328-b945a8cea5bd"),
                            Credits = 13,
                            Name = "Science"
                        },
                        new
                        {
                            Id = new Guid("f4515227-a87c-479e-b095-2806b568834a"),
                            Credits = 15,
                            Name = "Portuguese"
                        },
                        new
                        {
                            Id = new Guid("ff5ca171-cf9f-4388-8e58-ca7a82bed01e"),
                            Credits = 10,
                            Name = "Sport"
                        },
                        new
                        {
                            Id = new Guid("e21c1f02-3086-44b6-a247-81bfc65eda36"),
                            Credits = 9,
                            Name = "Philosophy"
                        },
                        new
                        {
                            Id = new Guid("238105e8-973d-4068-8c0e-e7fd7df6bab5"),
                            Credits = 13,
                            Name = "English"
                        },
                        new
                        {
                            Id = new Guid("8f1e73b4-3935-4b4f-946f-99bdcfec946a"),
                            Credits = 12,
                            Name = "Politics"
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Entities.Disenrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Disenrollments");
                });

            modelBuilder.Entity("StudentManagementSystem.Entities.Enrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fcfe2236-1655-45a2-a867-4029647cca27"),
                            CourseId = new Guid("1ec42a3c-9fb8-4148-b6ec-93a235ce6493"),
                            Grade = 0,
                            StudentId = new Guid("3fbccb11-f961-44fa-ba3f-8e208532cda0")
                        },
                        new
                        {
                            Id = new Guid("b6f6f081-454e-4e6f-92bf-e7ed5cee5efd"),
                            CourseId = new Guid("f4515227-a87c-479e-b095-2806b568834a"),
                            Grade = 0,
                            StudentId = new Guid("3fbccb11-f961-44fa-ba3f-8e208532cda0")
                        },
                        new
                        {
                            Id = new Guid("5af46425-d948-443b-a1fd-3fd063e0797a"),
                            CourseId = new Guid("1ec42a3c-9fb8-4148-b6ec-93a235ce6493"),
                            Grade = 0,
                            StudentId = new Guid("07ff3eda-b1ad-4227-8ac2-7154cb88e64b")
                        },
                        new
                        {
                            Id = new Guid("9993a8ca-46f4-4209-95c3-eaebe5053b27"),
                            CourseId = new Guid("f4515227-a87c-479e-b095-2806b568834a"),
                            Grade = 0,
                            StudentId = new Guid("07ff3eda-b1ad-4227-8ac2-7154cb88e64b")
                        },
                        new
                        {
                            Id = new Guid("33933691-6fc3-413e-bacd-a73429501b02"),
                            CourseId = new Guid("1ec42a3c-9fb8-4148-b6ec-93a235ce6493"),
                            Grade = 0,
                            StudentId = new Guid("49f8552a-12a9-4f0b-a872-a8aa31893089")
                        },
                        new
                        {
                            Id = new Guid("b2750a61-a3fe-4c11-bc24-4db15f2bdd48"),
                            CourseId = new Guid("f4515227-a87c-479e-b095-2806b568834a"),
                            Grade = 0,
                            StudentId = new Guid("49f8552a-12a9-4f0b-a872-a8aa31893089")
                        },
                        new
                        {
                            Id = new Guid("256c64bb-fc23-4428-a391-87c111d931c8"),
                            CourseId = new Guid("1ec42a3c-9fb8-4148-b6ec-93a235ce6493"),
                            Grade = 0,
                            StudentId = new Guid("dc8d125f-ae1a-4bc5-9068-f0ab152fc53f")
                        },
                        new
                        {
                            Id = new Guid("5f382af3-ed3e-4eb8-977f-3eabd6f8fb45"),
                            CourseId = new Guid("f4515227-a87c-479e-b095-2806b568834a"),
                            Grade = 0,
                            StudentId = new Guid("dc8d125f-ae1a-4bc5-9068-f0ab152fc53f")
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3fbccb11-f961-44fa-ba3f-8e208532cda0"),
                            Email = "student1@email.com",
                            Name = "student 1"
                        },
                        new
                        {
                            Id = new Guid("07ff3eda-b1ad-4227-8ac2-7154cb88e64b"),
                            Email = "student2@email.com",
                            Name = "student 2"
                        },
                        new
                        {
                            Id = new Guid("49f8552a-12a9-4f0b-a872-a8aa31893089"),
                            Email = "student3@email.com",
                            Name = "student 3"
                        },
                        new
                        {
                            Id = new Guid("dc8d125f-ae1a-4bc5-9068-f0ab152fc53f"),
                            Email = "student4@email.com",
                            Name = "student 4"
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Entities.Disenrollment", b =>
                {
                    b.HasOne("StudentManagementSystem.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.Entities.Student", "Student")
                        .WithMany("Disenrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentManagementSystem.Entities.Enrollment", b =>
                {
                    b.HasOne("StudentManagementSystem.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.Entities.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentManagementSystem.Entities.Student", b =>
                {
                    b.Navigation("Disenrollments");

                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
